### ISSUE TITLE
Your request type is not valid

### ISSUE THREAD

**Issue by rotacak** [norihiro/obs-shutdown-plugin#2]
Hello,

I using OBS 29.1.3 and cannot make it work. Where can be problem?
![bug](https://github.com/norihiro/obs-shutdown-plugin/assets/1352191/90b8a499-4234-45f7-a2db-229c36a0e31d)

**Comment by norihiro** [comment]
The field of `requestType` should be `CallVendorRequest` and the request to this plugin should be placed inside `requestData`.

Please have a look at this section.
https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#request-opcode-6

So, probably
```json
{
  "op": 6,
  "d": {
    "requestType": "CallVendorRequest",
    "requestId": "f819dcf0-89cc-11eb-8f0e-382c4ac93b9c",
    "requestData": {
      "vendorName": "obs-shutdown-plugin",
      "requestType": "shutdown",
      "requestData": request_object
    }
  }
}
```
`request_object` should be replaced by what you have written in the image.

**Comment by rotacak** [comment]
Thanks, it works.
